#!/bin/bash
cp ~/Downloads/sslforfree.zip sslforfree/
ls sslforfree
unzip sslforfree/sslforfree.zip -d sslforfree/
cp sslforfree/certificate.crt sslforfree/server.crt
echo "" >> sslforfree/server.crt
cat sslforfree/ca_bundle.crt >> sslforfree/server.crt
scp sslforfree/server.crt dariomac@dariomac.com:~/cert/server.crt.$(date +%s).bkp
scp sslforfree/server.crt dariomac@dariomac.com:~/cert/
scp sslforfree/private.key dariomac@dariomac.com:~/cert/private.key.$(date +%s).bkp
scp sslforfree/private.key dariomac@dariomac.com:~/cert/
