export const highlightWords = [
  '.net',
  'architect', 'asp.net', 'angular', 'ai', 'artificial intelligence', 'AOP',
  'blog posts',
  'c#', 'cibse', 'clei', 'cms', 'coo', 'conferences as speaker', 'cone of uncertainty',
  'decision making',
  'embedded visual basic 3.0', 'extremme programing', 'es6', 'estimations',
  'devops', 'drupal', 'devrel',
  'facebook instant articles',
  'google amp', 'google news',
  'html',
  'javascript', 'java', 'jsps', 'jsp', 'jquery', 'json',
  'kanban',
  'hp-jornada 720', 'hp ipaq-2210', 'highcharts js', 'handlebars',
  'linux',
  'master in engineering', 'master', 'mvc', 'mysql', 'msn', 'MSc',
  'nginx', 'nodejs', 'node.js', 'next.js',
  'oracle',
  'pm2', 'pm', 'postgresql',
  'quality assurance', 'quality',
  'ruby on rails', 'ruby', 'react', 'redis',
  'scrum master', 'scrum', 'scientific research', 'sdlc', 'social networks', 'sql server', 'sql', 'svg', 'software engineering professor', 'swebok', 'sanity',
  'tfs', 'typescript',
  'uml',
  'visual basic 6.0', 'vercel',
  'windows',
  'xp',
  'yaml'
];
